#!/bin/sh
set -eu
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root." >&2
	exit 1
fi

set -x

if ! mountpoint -q /boot/efi; then
	mount /boot/efi
fi

cd /usr/src/linux
NUM_JOBS=$(($(getconf _NPROCESSORS_ONLN) + 1))
make modules_prepare
make -j${NUM_JOBS} -l${NUM_JOBS}
emerge --ask=n @module-rebuild
make INSTALL_MOD_STRIP=1 modules_install
make install

eclean-kernel -n10
