#!/bin/sh
set -eu
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root." >&2
	exit 1
fi

set -x

cd /usr/src/linux
make -j49 -l49
make install
make INSTALL_MOD_STRIP=1 modules_install
emerge --ask=n @module-rebuild

read -r KERNVER < /usr/src/linux/include/config/kernel.release

dracut --force --hostonly --zstd --kver ${KERNVER}

if ! mountpoint -q /boot/efi; then
	mount /boot/efi
fi
# Requires one-shot efibootmgr setup:
# efibootmgr --create --part 2 --disk /dev/sda --label "stub" --loader '\EFI\gentoo\vmlinuz.efi' -u 'initrd=\EFI\gentoo\initramfs.img'
# Substitute partition/disk as necessary.
cp /boot/vmlinuz-${KERNVER} /boot/efi/EFI/gentoo/vmlinuz.efi
cp /boot/initramfs-${KERNVER}.img /boot/efi/EFI/gentoo/initramfs.img

eclean-kernel -n10
