#!/bin/sh
set -e
# To find your desired devices, run `for iommu_group in $(find /sys/kernel/iommu_groups/ -maxdepth 1 -mindepth 1 -type d); do echo "IOMMU group $(basename "$iommu_group")"; for device in $(ls -1 "$iommu_group"/devices/); do echo -n $'\t'; lspci -nns "$device"; done; done`.
# After this, call this script with vfio-bind 0000:[device number]

# This script assumes one has permissions to unbind PCI devices.
# This does not necessarily require root if udev rules are added.

for dev in "$@"; do
	read -r vendor < /sys/bus/pci/devices/$dev/vendor
	read -r device < /sys/bus/pci/devices/$dev/device
	if [ -e /sys/bus/pci/devices/$dev/driver ]; then
		echo $dev > /sys/bus/pci/devices/$dev/driver/unbind
	fi
	echo $vendor $device > /sys/bus/pci/drivers/vfio-pci/new_id
done
